<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Effective Tips  To improve your Health _e901fd</name>
   <tag></tag>
   <elementGuidId>2b4fb747-dd28-4c74-af25-10ab7ebed8b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='print-section']/div/div/div/div[2]/div/div[5]/div/div/div[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fxlayout</name>
      <type>Main</type>
      <value>column</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Effective Tips  To improve your Health &amp; Wellbeing  Take your eye exam atleast once in a year  Regularly walk for every day  Take adequate sleep for 6-8 hrs every day  Restrict salt intake to less than 1 teaspoon per day  Take your eye exam at least once a year  Take adequate sleep for atleast 6-8 hrs everyday  Regularly walk for 30 mins every day  Keep checking your fasting blood sugar levels everyday  Do 20-60 mins of aerobic exercise everyday and avoid resistance training  Monitor blood pressure regularly  Do breathing exercises regularly  Avoid smoking and exposure to dust or allergen  Consume 4/5L of fuids, which will help drain the secretions  Keep reminders for day to day activities  Wear a medic alert bracelet  Care-takers should be made aware that depression can coexist </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;print-section&quot;)/div[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;header ng-star-inserted&quot;]/div[@class=&quot;print-container&quot;]/div[@class=&quot;main-mg ng-star-inserted&quot;]/div[1]/div[5]/div[@class=&quot;effective-print ng-star-inserted&quot;]/div[1]/div[2]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='print-section']/div/div/div/div[2]/div/div[5]/div/div/div[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order Medicine'])[1]/following::div[7]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Consult Doctor'])[1]/following::div[9]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div[2]</value>
   </webElementXpaths>
</WebElementEntity>
